version: '3'

services:
  db:
    image: postgres:14.4
    environment: 
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - default