FROM node:18.13.0
# Installing libvips-dev for sharp Compatability
RUN apt-get update && apt-get install libvips-dev -y
ARG NODE_ENV=development
ARG URL=cms
ENV URL=${URL}
ENV NODE_ENV=${NODE_ENV}
WORKDIR /app
COPY ./package.json .
COPY ./package-lock.json .

RUN npm install
COPY ./ .

RUN npm run build
EXPOSE 1337

CMD ["npm","run", "develop"]