import type {
  NextPage,
  GetStaticProps, 
  InferGetStaticPropsType} from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useContext } from 'react'
import ItemList from '../components/ItemList'
import { AppContext } from '../context/AppContext'
import { fetchAPI } from '../lib/api'
import { FrontPageFields } from '../utils/models'

export const getStaticProps: GetStaticProps<{content: FrontPageFields}> = async (context) => {
  const [content] = await Promise.all([
    fetchAPI<FrontPageFields>('/front-page',{},{
      locale: context.locale,
    })
  ]);
  return {
    props: {
      content,
    },
    revalidate: 60,
  }
}

type PropType = InferGetStaticPropsType<typeof getStaticProps>

const Home: NextPage<PropType> = ({content}) => {
  const {items} = useContext(AppContext)
  const { title, bodyText } = content.attributes;

  return (
    <div>
      <Head>
        <title>Ilmotunkki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container mx-auto px-4'>
        <h1 className='font-medium leading-tight text-5xl'>{title}</h1>
          <p className="text-base mt-0 mb-4">
            {bodyText}
          </p>
          <ItemList />
          {items.length > 0 && 
          <Link href={'/contact'} passHref>
            <a className="btn">Seuraava</a>
          </Link>}
      </main>
    </div>
  )
}

export default Home
