FROM node:20.6.1

WORKDIR /app

COPY ./package.json .
COPY ./package-lock.json .

RUN npm install

COPY ./ .


ARG PRIMARY_COLOR
ARG SECONDARY_COLOR

ENV PRIMARY_COLOR=${PRIMARY_COLOR}
ENV SECONDARY_COLOR=${SECONDARY_COLOR}

EXPOSE 3000

CMD ["npm", "run", "develop"]